### ISSUE TITLE
语法分析器的类型转换/映射错误？

### ISSUE THREAD

**Issue by Samshui** [BUAA-SE-Compiling/miniplc0-java#3]
测试代码testin：
```
begin
   const b = 2;
end
```
位置：Analyser.java - analyseConstantDeclaration()：
```
// 加入符号表
            String name = (String) nameToken.getValue();
```
分别采取不修改pull下来的代码，和小改动，结果如下：
---
①不改掉
报错：**java.lang.ClassCastException: class java.lang.StringBuilder cannot be cast to class java.lang.String (java.lang.StringBuilder and java.lang.String are in module java.base of loader 'bootstrap')**

②改为  `String name = nameToken.getValueString();`
报错：**Exception in thread "main" java.lang.Error: No suitable cast for token value.
        at miniplc0java.tokenizer.Token.getValueString(Token.java:48)
        at miniplc0java.analyser.Analyser.analyseConstantDeclaration(Analyser.java:239)
        at miniplc0java.analyser.Analyser.analyseMain(Analyser.java:217)
        at miniplc0java.analyser.Analyser.analyseProgram(Analyser.java:206)
        at miniplc0java.analyser.Analyser.analyse(Analyser.java:37)
        at miniplc0java.App.main(App.java:100)**

③最后改为` String name = nameToken.getValue().toString();` 似乎解决了

**Comment by Samshui** [comment]
我认罪，我自己的Tokenizer挖的坑，dbq.jpg

**Comment by lynzrand** [comment]
![图片](https://user-images.githubusercontent.com/10259119/97100420-5e885880-16ce-11eb-8dca-6571e886bf8c.png)

![图片](https://user-images.githubusercontent.com/10259119/97100422-60eab280-16ce-11eb-85f2-aa55ee469ddc.png)

closed due to consumer issues
